/**
 * GPU struct layouts, read from a build-time descriptor.
 *
 * The desktop analogue is `particle_system/layout.py`, which regex-parses
 * `shared/shaders/common.glsl` at import to build numpy dtypes. **This module is
 * NOT a port of that parser.** Per `docs/WEB_PORT_PLAN.md` step 2, the parser
 * stays in Python and runs at build time; `web/tools/generate_web_data.py` ships
 * its answer as `layout.generated.json` and this module reads it.
 *
 * Why not port the parser: shader hot-reload is gone (ARCHITECTURE.md invariant
 * 5), so a *runtime* parser has no job, and a second implementation of a strict
 * parser is a second thing that can be subtly wrong. Resist porting the regexes
 * for symmetry -- there is nothing here for them to do.
 *
 * ## Why this module asserts rather than merely reads
 *
 * `layout.py`'s header states the hazard plainly: a struct layout mismatch
 * "does not crash or error at runtime -- it silently reinterprets memory, and
 * the simulation just behaves subtly wrong. Failing loudly at startup is the
 * entire point."
 *
 * The desktop gets that for free because it re-parses the .glsl every run. The
 * port cannot: it reads a *snapshot*, so the failure mode moves from "the file
 * is malformed" to "the snapshot is stale." Hence the assertions below. They run
 * at module load, which is the port's equivalent of `layout.py:151-153`'s
 * "parsed once at import ... not at the first buffer upload."
 *
 * The assertion that earns the design is `assertLaneMap`, called from
 * `config.ts`: it checks the hand-written lane constants against the generated
 * offsets, so adding a vec4 to `ConfigData` fails loudly instead of silently
 * shifting every lane by four floats.
 */

import descriptor from './layout.generated.json' with { type: 'json' };

/** One member of a GPU struct, as the generator describes it. */
export interface LayoutMember {
  readonly name: string;
  /** Byte offset from the start of the struct. Always 16-byte aligned. */
  readonly offset: number;
  readonly size: number;
  /** `'vec4'`, or the name of a struct declared earlier in `common.glsl`. */
  readonly type: string;
  /** `offset / 4` -- the index into a Float32Array view of the record. */
  readonly floatIndex: number;
  readonly floatCount: number;
  /** Present only for array members; `Rule.centers` is the only one. */
  readonly arrayLength?: number;
  readonly stride?: number;
}

export interface LayoutStruct {
  readonly size: number;
  readonly float32Count: number;
  readonly members: readonly LayoutMember[];
}

const structs = descriptor.structs as unknown as Readonly<Record<string, LayoutStruct>>;

/** Look up a struct, failing loudly rather than returning undefined. */
export function layoutOf(name: string): LayoutStruct {
  const struct = structs[name];
  if (struct === undefined) {
    throw new Error(
      `layout.generated.json has no struct "${name}". Either common.glsl no ` +
        `longer declares it, or the descriptor is stale -- regenerate with ` +
        `\`npm run gen:web-data\`.`,
    );
  }
  return struct;
}

/** Byte offset of a named member, failing loudly if it is gone. */
export function memberOf(structName: string, memberName: string): LayoutMember {
  const member = layoutOf(structName).members.find((m) => m.name === memberName);
  if (member === undefined) {
    throw new Error(
      `struct ${structName} has no member "${memberName}" in ` +
        `layout.generated.json. Regenerate with \`npm run gen:web-data\`.`,
    );
  }
  return member;
}

export const CONFIG_DATA = layoutOf('ConfigData');
export const WORLD_DATA = layoutOf('WorldData');
export const ENTITY = layoutOf('Entity');

/**
 * Stride between consecutive `ConfigData` records in the ConfigBuffer.
 * The analogue of `layout.py:160`'s `SIZE_OF_CONFIG_DATA`.
 */
export const CONFIG_DATA_STRIDE = CONFIG_DATA.size;
export const WORLD_DATA_SIZE = WORLD_DATA.size;
/**
 * The analogue of `layout.py:159`'s `SIZE_OF_ENTITY_STRUCT`. Nothing in step 2
 * packs an entity -- this is here for steps 4 and 6, which do.
 */
export const ENTITY_STRIDE = ENTITY.size;

/** Float32 lanes per ConfigData record. 416 / 4 = 104. */
export const CONFIG_DATA_FLOATS = CONFIG_DATA.float32Count;

/**
 * Sizes the port hardcodes as strides, checked at module load.
 *
 * The generator checks these too (`EXPECTED_SIZES`), so this looks redundant --
 * but the generator only runs on a machine with the Python venv. This catches a
 * descriptor that was hand-edited, partially merged, or regenerated by a future
 * version of the generator that dropped the check.
 */
const EXPECTED_SIZES: Readonly<Record<string, number>> = {
  FourierCenter: 32,
  Rule: 320,
  ConfigData: 416,
  WorldData: 32,
  Entity: 32,
};

for (const [name, expected] of Object.entries(EXPECTED_SIZES)) {
  const actual = layoutOf(name).size;
  if (actual !== expected) {
    throw new Error(
      `struct ${name} is ${actual} bytes in layout.generated.json, expected ` +
        `${expected}. Every hardcoded stride in web/src/particleSystem assumes ` +
        `the expected value.`,
    );
  }
}

// `Rule.centers` is the one array member in the whole layout, and its stride is
// the number docs/WEB_PORT_PLAN.md step 3 calls out: std430's array-of-struct
// stride already equals WGSL's `array<FourierCenter,10>` stride, so there is no
// stride divergence to work around. Assert it rather than trusting the note.
{
  const centers = memberOf('Rule', 'centers');
  if (centers.stride !== 32 || centers.arrayLength !== 10) {
    throw new Error(
      `Rule.centers is ${centers.arrayLength} x ${centers.stride} bytes, ` +
        `expected 10 x 32. WGSL's array<FourierCenter,10> stride would no ` +
        `longer match std430's.`,
    );
  }
}

// The vec4-only rule, re-checked on this side. `layout.py:125-142`
// (`_assert_vec4_aligned`) runs the same check at parse time; repeating it here
// means a hand-edited descriptor is caught too, and it keeps the rule visible in
// the TypeScript rather than being an off-stage Python guarantee.
for (const [name, struct] of Object.entries(structs)) {
  if (struct.size % 16 !== 0) {
    throw new Error(
      `struct ${name} is ${struct.size} bytes, not a multiple of 16.`,
    );
  }
  for (const member of struct.members) {
    if (member.offset % 16 !== 0) {
      throw new Error(
        `struct ${name}: member "${member.name}" is at offset ${member.offset}, ` +
          `not 16-byte aligned.`,
      );
    }
  }
}

/**
 * Check hand-written float-lane constants against the generated offsets.
 *
 * **This is the assertion the whole descriptor design exists for.** `config.ts`
 * states which float means what (`LANE`); the descriptor states where each vec4
 * begins. If someone adds a `vec4` to `ConfigData` in `common.glsl` and
 * regenerates, every lane after the insertion point shifts by four floats -- and
 * without this check the port would keep writing `hazard_rate` where the shader
 * now reads something else. No error, no crash, just subtly wrong physics.
 *
 * Called from `config.ts` at module load rather than declared there, so the
 * failure surfaces at import time on the first thing that touches a config.
 */
export function assertLaneMap(
  structName: string,
  lanes: Readonly<Record<string, number>>,
): void {
  const struct = layoutOf(structName);
  for (const [memberName, lane] of Object.entries(lanes)) {
    const member = struct.members.find(
      (m) => m.name.toLowerCase() === memberName.toLowerCase(),
    );
    if (member === undefined) {
      throw new Error(
        `${structName} has no member matching lane constant "${memberName}". ` +
          `Either common.glsl renamed it or the LANE table is stale.`,
      );
    }
    if (member.floatIndex !== lane) {
      throw new Error(
        `${structName}.${member.name} is at float lane ${member.floatIndex} in ` +
          `layout.generated.json, but the LANE table says ${lane}. The struct ` +
          `changed and the lane constants did not follow -- packing would write ` +
          `every field after this point into the wrong place, silently.`,
      );
    }
  }
}
